name: Setup infrastructure for app
# This file defines a workflow that calls the btp-setup-automator and deploys a
# use case around building resilient apps 
# see https://github.com/SAP-samples/btp-build-resilient-apps

on:
  workflow_dispatch:

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
    setup-infrastructure:
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/rui1610/tf_cap:main
          options: --user root
        env: 
            BTP_USERNAME: ${{ secrets.BTP_USERNAME }}
            BTP_PASSWORD: ${{ secrets.BTP_PASSWORD }}
        steps:
          - name: Set up Git repository
            uses: actions/checkout@v3
          - name: "Get repo folder in container"
            shell: bash
            run: |
              echo "REPO_NAME=/__w/$(basename ${{ github.repository }})/$(basename ${{ github.repository }})" >> $GITHUB_ENV
          - name: 'Run Terraform script'
            if: ${{ always() }}
            working-directory:  $GOPATH
            shell: bash
            run: |
              cd ${{ env.REPO_NAME }}/terraform
              ls -l
              terraform version