name: Temp

on:
  workflow_dispatch:

env:
  TARGET_BRANCH: main
  CF_METADATA_FILENAME: cloudfoundry.tfvars

# Taken from https://github.com/hashicorp/setup-terraform
jobs:
  check-if-cf-file-exists:
    name: Check if Cloudfoundry metadata is known
    runs-on: ubuntu-latest
    outputs:
      cf_metadatafile_exists: ${{ steps.cf_metadata_exists.outputs.cf_metadatafile_exists }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: ${{ env.TARGET_BRANCH }}
    - name: Terraform Apply
      id: cf_metadata_exists
      working-directory: terraform
      shell: bash
      run: |
        test -f $CF_METADATA_FILENAME && echo "cf_metadatafile_exists=false" >> $GITHUB_OUTPUT && echo "The CF metadata file exists!"

  infrastructure1:
    if: ${{needs.check-if-cf-file-exists.outputs.cf_metadatafile_exists}} == 'true'
    name: Run Terraform script
    runs-on: ubuntu-latest
    needs: [check-if-cf-file-exists]
    outputs:
      cloudfoundry_org_id: ${{ steps.terraform_output.outputs.cloudfoundry_org_id }}
      subaccount_id: ${{ steps.terraform_output.outputs.subaccount_id }}
      subaccount_name: ${{ steps.terraform_output.outputs.subaccount_name }}
      cloudfoundry_space_id: ${{ steps.terraform_output.outputs.cloudfoundry_space_id }}
    steps:
    - name: Checkout Repo
      shell: bash
      run: |
        echo "${{needs.check-if-cf-file-exists.outputs.cf_metadatafile_exists}}"
        echo ${{needs.check-if-cf-file-exists.outputs.cf_metadatafile_exists}}

 