name: Test Github output
# This file defines a workflow that calls the btp-setup-automator and deploys a
# use case around building resilient apps 
# see https://github.com/SAP-samples/btp-build-resilient-apps

on:
  workflow_dispatch:

  pull_request:
    types: [closed]
    branches:
      - main

# Taken from https://github.com/hashicorp/setup-terraform
jobs:
  temp1:
    name: Run Terraform script
    runs-on: ubuntu-latest
    outputs:
      cf_org: ${{ steps.terraform_output.outputs.cf_org }}
    steps:
    - name: Extract data from Terraform run
      id: terraform_output
      run: |
        echo "cf_org=cf_orgname-1234567" >> $GITHUB_OUTPUT

  deploy-cap-application:
    name: Deploy CAP application
    runs-on: ubuntu-latest
    needs: temp1
    steps:
    - name: 'Check output'
#      working-directory: /home/user
      shell: bash
      env:
        CF_ORG: ${{needs.temp1.outputs.cf_org}}
 
      run: |
        pwd
        ls -l
        echo ${{ env.CF_ORG }}
