name: Temp
on:
  workflow_dispatch:

  pull_request:
    types: [closed]
    branches:
      - main

env:
  TARGET_BRANCH: main
  CF_METADATA_FILENAME: cloudfoundry.tfvars

# Taken from https://github.com/hashicorp/setup-terraform
jobs:
  check-if-cf-file-exists:
    name: Check if Cloudfoundry metadata is known
    runs-on: ubuntu-latest
    outputs:
      cf_metadatafile_exists: ${{ steps.cf_metadata_exists.outputs.cf_metadatafile_exists }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: ${{ env.TARGET_BRANCH }}
    - name: Check existance of CF file
      id: cf_metadata_exists
      working-directory: terraform
      shell: bash
      run: |
        if [ -f "$CF_METADATA_FILENAME" ]; then
            echo "cf_metadatafile_exists=true" >> $GITHUB_OUTPUT && echo "The CF metadata file exists!"
            export "$(grep -vE "^(#.*|\s*)$" $CF_METADATA_FILENAME)"
            echo $cloudfoundry_org_id
        else 
            echo "cf_metadatafile_exists=false" >> $GITHUB_OUTPUT && echo "The CF metadata file doesn't exist!"
        fi
    - name: "Get repo folder in container"
      shell: bash
      run: |
        echo "REPO_NAME=/__w/$(basename ${{ github.repository }})/$(basename ${{ github.repository }})" >> $GITHUB_ENV
